stages:
    - versioning
    - checks
    - container_build
    - retag
    - push
    - clean_up

versioning and prepare:
    stage: versioning
    script:
        - git submodule update --init --recursive
        - echo "Version is $CI_COMMIT_BRANCH.$CI_PIPELINE_ID"
    tags:
        - linux
    artifacts:
        paths:
            - ./solana-tools/

clippy:
    stage: checks
    image: rust:1.76.0
    script:
        - rustup default 1.76.0
        - rustup component add clippy
        - cargo clippy --all-targets -- -Dwarnings
    tags:
        - docker

build_solana:
    stage: container_build
    script:
        - docker build -t 899260217834.dkr.ecr.us-east-1.amazonaws.com/udf-oracle-solana:$CI_COMMIT_BRANCH.$CI_PIPELINE_ID -t 899260217834.dkr.ecr.us-east-1.amazonaws.com/udf-oracle-solana:latest -f ./docker/Dockerfile_solana .
    tags:
        - linux

build_module:
    stage: container_build
    script:
        - docker build -t 899260217834.dkr.ecr.us-east-1.amazonaws.com/udf-publisher-solana:$CI_COMMIT_BRANCH.$CI_PIPELINE_ID -t 899260217834.dkr.ecr.us-east-1.amazonaws.com/udf-publisher-solana:latest -f ./docker/Dockerfile_module .
    tags:
        - linux

retag:
    stage: retag
    script:
        - docker tag 899260217834.dkr.ecr.us-east-1.amazonaws.com/udf-publisher-solana:$CI_COMMIT_BRANCH.$CI_PIPELINE_ID 899260217834.dkr.ecr.us-east-1.amazonaws.com/udf-publisher-solana:$CI_COMMIT_BRANCH.latest
    only:
        - testnet
        - mainnet
        - develop
    tags:
        - linux

module_push:
    stage: push
    script:
        - docker push 899260217834.dkr.ecr.us-east-1.amazonaws.com/udf-publisher-solana:$CI_COMMIT_BRANCH.$CI_PIPELINE_ID
        - docker push 899260217834.dkr.ecr.us-east-1.amazonaws.com/udf-publisher-solana:$CI_COMMIT_BRANCH.latest
    only:
        - testnet
        - mainnet
        - develop
    tags:
        - linux

clean_up_images:
    stage: clean_up
    script:
        - docker rmi 899260217834.dkr.ecr.us-east-1.amazonaws.com/udf-publisher-solana:$CI_COMMIT_BRANCH.$CI_PIPELINE_ID -f
        - docker rmi 899260217834.dkr.ecr.us-east-1.amazonaws.com/udf-publisher-solana:$CI_COMMIT_BRANCH.latest || true
        - docker rmi 899260217834.dkr.ecr.us-east-1.amazonaws.com/udf-oracle-solana:$CI_COMMIT_BRANCH.$CI_PIPELINE_ID -f
        - docker rmi 899260217834.dkr.ecr.us-east-1.amazonaws.com/photon-module:latest || true
    tags:
        - linux
