FROM solanalabs/rust:1.75.0
RUN sh -c "$(curl -sSfL https://release.solana.com/v1.18.4/install)" && \
    /root/.local/share/solana/install/active_release/bin/sdk/sbf/scripts/install.sh
ENV PATH=/root/.local/share/solana/install/active_release/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN cargo install --git https://github.com/coral-xyz/anchor --tag v0.29.0 avm --locked --force && \
    avm install 0.29.0 && avm use 0.29.0
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN rm -f /usr/share/keyrings/githubcli-archive-keyring.gpg && \
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --batch --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
    apt update
RUN apt -y install yarn python3 net-tools
RUN apt clean && rm -rf /var/lib/apt/lists/* /var/lib/apt/cache/*
RUN solana-keygen new -f -s --no-bip39-passphrase
RUN solana config set --url http://localhost:8899
COPY . /price-oracle-sc-solana/
RUN yarn install --cwd /price-oracle-sc-solana/
COPY keys/*-keypair.json /price-oracle-sc-solana/target/deploy/
WORKDIR /price-oracle-sc-solana/
RUN --mount=type=cache,target=./target,sharing=locked --mount=type=cache,target=/usr/local/cargo/registry  docker/build_solana_test_state.sh
#ENTRYPOINT ["solana-test-validator"]
